# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mimic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmimic.proto\x12\x02pb\"\x1c\n\nMsgRequest\x12\x0e\n\x06signal\x18\x01 \x01(\t\"\x1a\n\x0bMsgResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t27\n\x08Messages\x12+\n\x06\x44\x65tect\x12\x0e.pb.MsgRequest\x1a\x0f.pb.MsgResponse\"\x00\x42 Z\x1egithub.com/jonreesman/mimic/pbb\x06proto3')



_MSGREQUEST = DESCRIPTOR.message_types_by_name['MsgRequest']
_MSGRESPONSE = DESCRIPTOR.message_types_by_name['MsgResponse']
MsgRequest = _reflection.GeneratedProtocolMessageType('MsgRequest', (_message.Message,), {
  'DESCRIPTOR' : _MSGREQUEST,
  '__module__' : 'mimic_pb2'
  # @@protoc_insertion_point(class_scope:pb.MsgRequest)
  })
_sym_db.RegisterMessage(MsgRequest)

MsgResponse = _reflection.GeneratedProtocolMessageType('MsgResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGRESPONSE,
  '__module__' : 'mimic_pb2'
  # @@protoc_insertion_point(class_scope:pb.MsgResponse)
  })
_sym_db.RegisterMessage(MsgResponse)

_MESSAGES = DESCRIPTOR.services_by_name['Messages']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036github.com/jonreesman/mimic/pb'
  _MSGREQUEST._serialized_start=19
  _MSGREQUEST._serialized_end=47
  _MSGRESPONSE._serialized_start=49
  _MSGRESPONSE._serialized_end=75
  _MESSAGES._serialized_start=77
  _MESSAGES._serialized_end=132
# @@protoc_insertion_point(module_scope)
